export const TOPIC_EMOJIS: { [key: string]: string } = {
  

    // Additional Topics
    "ELECTRICITY & MAGNETISM: Electric circuits": "🔌",
    "CAPS TOPIC MEASUREMENT MAPS, PLANS & OTHER REPRESENTATIONS OF THE PHYSICAL WORLD": "🗺️",
    "FINANCE": "💰",
    "DATA HANDLING": "📊",
    "Calculate surface area and volume of cylinders, cones, spheres and prisms": "🧊",
    "Use graphs to solve real-life problems (e.g. motion, cost)": "📈",
    "Interpret displacement and velocity vectors in applied problems": "➡️",
    "Convert between metric units and imperial units": "🔄",
    "Identify and continue number patterns with constant first or second differences": "🔢",
    "Solve linear equations and simple inequalities": "➗",
    "Apply the angle properties of triangles, quadrilaterals and parallel lines": "📐",
    "Convert units of length, area, volume and time": "🔄",
    "Simplify expressions using laws of exponents (including zero and negative powers)": "🔣",
    "Expand and factorise algebraic expressions with monomials and binomials": "🧬",
    "Perform percentage calculations involving profit, loss, discount and VAT": "💹",
    "Work with simple interest calculations": "💰",
    "Solve problems involving budgets and bank statements": "💵",
    "Formulate rules for patterns using algebraic expressions": "🔗",
    "Recognise and use algebraic notation": "🔣",
    "Apply the rules for addition, subtraction, multiplication, and division of integers": "➕",
    "Substitute values into expressions and solve simple equations": "🧮",
    "Simplify algebraic expressions using basic rules": "🔣",
    "Identify number patterns with a constant difference": "🔢",
    "Solve real-life problems involving percentages (e.g. discounts, increases)": "💯",
    "Estimate and measure using appropriate tools": "📏",
    "Perform calculations with positive and negative integers": "➖",
    "Perform calculations with fractions and decimals": "➗",
    "Convert between fractions, decimals, and percentages": "🔄",
    "Describe and extend numeric and geometric patterns": "🔢",
    "Use patterns to generate simple rules or expressions": "🔗",
    "Complete input-output tables for simple functions": "📋",
    "Identify types of angles and measure them with a protractor": "📐",
};

// Subtopic emoji map for maths topics
// prettier-ignore
const SUBTOPIC_EMOJIS: { [key: string]: string } = {
  "Solve quadratic and cubic equations algebraically": "🧩",
  "Solve inequalities and represent solutions graphically": "📈",
  "Calculate the sum to infinity for geometric series": "♾️",
  "Recognize and work with arithmetic and geometric sequences": "🔢",
  "Use derivatives to find gradients, tangents, maxima and minima": "📐",
  "Determine the equation of inverse and composite functions": "🔄",
  "Sketch and interpret cubic, exponential, and logarithmic functions": "📊",
  "Simplify rational expressions and solve rational equations": "🧮",
  "Apply transformations to function graphs": "🔃",
  "Work with present and future value formulas": "💸",
  "Calculate simple and compound interest": "💰",
  "Calculate and interpret standard deviation and variance": "📏",
  "Calculate the distance, gradient and midpoint between two points": "📏",
  "Differentiate polynomials using rules of differentiation": "➗",
  "Use box plots and cumulative frequency graphs": "📦",
  "Use scalar (dot) product to find angles between vectors": "📐",
  "Apply the addition and multiplication rules of probability": "🎲",
  "NO MATCH AI": "❓",
  "Find the equation of a circle and a tangent to a circle": "⚪️",
  "Simplify and prove trigonometric identities": "📐",
  "Solve problems using vector geometry": "➡️",
  "Use coordinate methods for proofs in geometry": "📏",
  "Apply annuity and amortization formulas to real-life problems": "🏦",
  "Apply first principles of differentiation": "📝",
  "Use Venn diagrams and tree diagrams for compound events": "🌳",
  "Calculate and interpret conditional probability": "🧮",
  "Interpret skewness using mean, median, and mode": "📊",
  "Solve trigonometric equations for general solutions": "📐",
  "Model real-life situations using trigonometric graphs": "📈",
  "Solve linear and quadratic equations algebraically": "🧩",
  "Factorise expressions using common factors and trinomials": "🧬",
  "Determine the equation of a linear or quadratic function": "📏",
  "Use graphs to solve equations and inequalities": "📉",
  "Simplify algebraic expressions using laws of exponents": "🔣",
  "Solve real-world problems involving savings and loans": "💵",
  "Convert between units of measurement": "🔄",
  "Find the length of a line segment using the distance formula": "📏",
  "Calculate simple and compound interest over time": "💰",
  "Determine the probability of simple events": "🎲",
  "Understand complementary and equally likely outcomes": "⚖️",
  "Collect, organise and represent data using tables and graphs": "📋",
  "Factorise and solve quadratic equations": "🧬",
  "Understand domain, range, and restrictions on functions": "📐",
  "Simplify expressions using exponents and scientific notation": "🔢",
  "Understand and use sine, cosine and tangent ratios": "📐",
  "Identify linear and quadratic patterns": "🔗",
  "Determine the gradient and midpoint between two points": "📏",
  "Understand basic relationships between lines (e.g. parallel, perpendicular)": "📐",
  "Calculate area and perimeter of 2D shapes": "📐",
  "Identify types of angles and triangles": "🔺",
  "Solve simultaneous linear equations algebraically and graphically": "➗",
  "Use geometric reasoning in problem solving": "📏",
  "Draw and interpret linear and quadratic graphs from tables": "📊",
  "Interpret and compare data sets using range and spread": "📊",
  "Solve two-dimensional problems using the sine and cosine rules": "📐",
  "Calculate measures of central tendency (mean, median, mode)": "📊",
  "Work with arithmetic and geometric sequences": "🔢",
  "Interpret trigonometric values in context": "📐",
  "Solve right-angled triangle problems using trigonometry": "🔺",
  "Calculate volume and surface area of 3D objects": "📦",
  "Apply basic theorems involving angles in triangles and parallel lines": "📐",
  "Calculate mean, median, mode and range from ungrouped data": "📊",
  "Apply basic circle theorems (angles in the same segment, cyclic quadrilateral)": "⚪️",
  "Use congruency and similarity in geometric proofs": "🟰",
  "Recognize patterns and describe them using formulae": "🔗",
  "Determine the equation of a function from its graph": "📈",
  "Determine the equation of a line given certain conditions": "📏",
  "Calculate distance, gradient, and midpoint between two points": "📏",
  "Sketch and interpret linear, quadratic, exponential and hyperbolic graphs": "📊",
  "Draw and interpret histograms and box-and-whisker plots": "📦",
  "Compare data distributions using interquartile range": "📊",
  "Prove geometric relationships using coordinate geometry": "📏",
  "Use the sine, cosine and tangent ratios in right-angled triangles": "📐",
  "Solve problems using vector components in 2D": "➡️",
  "Sketch and interpret basic trig graphs": "📈",
  "Use sigma notation for summation": "∑",
  "Generate rules for number sequences": "🔢",
  "Solve linear and quadratic equations using factorisation and the quadratic formula": "🧩",
  "Manipulate algebraic expressions and solve for unknowns": "🔣",
  "Solve simultaneous equations algebraically and graphically": "➗",
  "Interpret and draw linear, quadratic, and exponential graphs": "📊",
  "Apply exponential growth and decay in technical contexts (e.g. depreciation)": "📈",
  "Understand and apply rate of change in graphs": "📉",
  "Solve right-angled triangle problems using sine, cosine and tangent": "🔺",
  "Understand and apply basic angle rules (e.g. angles on a straight line)": "📐",
  "Classify 2D shapes by properties (sides, angles, symmetry)": "🔷",
  "Calculate perimeter and area of basic 2D shapes": "📏",
  "Plot and interpret points on a Cartesian plane": "🗺️",
  "Represent data using bar graphs and pie charts": "📊🥧",
  "Identify linear patterns in tables and graphs": "📈🔗",
  "Solve problems involving 2D shapes and angles": "🔺📐",
  "Calculate perimeter, area and volume of composite shapes": "🧊📏",
  "Interpret and use values from a calculator": "🧮",
  "Apply pattern rules to solve problems": "🔢🧩",
  "Solve problems using linear equations and graphs": "➗📈",
  "Draw graphs to represent relationships between variables": "📈🔄",
};

export default SUBTOPIC_EMOJIS; 